### ISSUE TITLE
Not working with new HA 2026.4.0

### ISSUE THREAD

**Issue by p6002** [fcrohas/hassio-bk-light#1]
My HA:
Core
2026.4.0
Supervisor
2026.03.2
Operating System
17.1

`Error while setting up bk_light platform for image: ImageEntity.__init__() missing 1 required positional argument: 'hass'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/bk_light/image.py", line 39, in async_setup_entry
    async_add_entities([BKLightImageEntity(device, config_entry)], True)
                        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bk_light/image.py", line 50, in __init__
    super().__init__()
    ~~~~~~~~~~~~~~~~^^
TypeError: ImageEntity.__init__() missing 1 required positional argument: 'hass'`

**Comment by TBR-BRD** [comment]
i have the same Problem, please help

**Comment by TBR-BRD** [comment]
It works: https://github.com/TBR-BRD/ha-action-32x32-led
